for(i1=0;i1<4;i1++){
    for(i2=0;i2<5;i2++){
        if(i2%2==0){
            document.write("★");
        }else{
            document.write("☆");
        }
    }
    document.write("<br>");
}